describe('continents spec', () => {
  beforeEach(() => {
    cy.intercept('https://countries.trevorblades.com/',
      cy.stub()
        .callsFake(req => req.reply({ fixture: 'trivia.json' }))).as('continents')
    cy.visit('http://localhost:3000/selections')
    cy.wait('@continents')
    cy.get('.continent-buttons > div > :nth-child(2)').click()
    cy.get('[name="emoji"]').click()
  })

  it('Should display title and question', () => {
    cy.get('[data-cy="title"]').contains('Trivia Game')
    cy.get('.which-question').contains("Which country's flag is this?")
    cy.get('.emoji').should('exist')
  });

  it('Should display four questions', () => {
    cy.get('#mc-a').should('exist')
    cy.get('#mc-b').should('exist')
    cy.get('#mc-c').should('exist')
    cy.get('#mc-d').should('exist')
  });

  it('Should color correct and incorrect responses', () => {
    cy.get('#mc-a').should('exist').click()
      .should('have.css', 'background-color', 'rgb(148, 181, 99)')
    cy.get('#mc-b').should('exist').click()
      .should('have.css', 'background-color', 'rgb(249, 0, 0)')
  });

  it('Should serve the user 10 questions then show score', () => {
    cy.get('#mc-a').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('h2.which-question').contains('You got 1/10 correct!')
    cy.get('h1.which-question').contains('Click the logo to return home')
  });

  it('Should allow user to return home after a round', () => {
    cy.get('#mc-a').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('[data-cy="title"]').click()
    cy.get('[data-cy="select-game-btn"]').should('exist')
  });

  it('Should be able to select flags or capitals', () => {
    cy.get('#mc-a').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('[data-cy="title"]').click()
    cy.get('[data-cy="select-game-btn"]').click()
    cy.get('.continent-buttons > div > :nth-child(2)').click()
    cy.get('[name="capital"]').click()
    cy.get('.which-question').contains("Which country's capital is this?")
    cy.get('#mc-a').should('exist')
    cy.get('#mc-b').should('exist')
    cy.get('#mc-c').should('exist')
    cy.get('#mc-d').should('exist')
  });

  it('Should be able to select South America or Europe', () => {
    cy.get('#mc-a').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('#mc-b').click()
    cy.get('.next-button').click()
    cy.get('[data-cy="title"]').click()
    cy.get('[data-cy="select-game-btn"]').click()
    cy.get('.continent-buttons > div > :nth-child(1)').click()
    cy.get('[name="capital"]').click()
    cy.get('#mc-a').should('exist')
    cy.get('#mc-b').should('exist')
    cy.get('#mc-c').should('exist')
    cy.get('#mc-d').should('exist')
  });

})

